### ISSUE TITLE
Make pycalphad use PEP 518 to improve build requirements

### ISSUE THREAD

**Issue by toastedcrumpets** [pycalphad/pycalphad#309]
Currently Cython must be installed *before* pycalphad, in separate `pip install` commands; however, modern CI practices tend to install all packages via a single `requirements.txt` file.

[PEP 518 ](https://www.python.org/dev/peps/pep-0518/) adds a mechanism to properly resolve build dependencies by adding a `pyproject.toml` file. I think a minimal implementation for pycalphad would be the following

```
[build-system]
# Minimum requirements for the build system to execute.
requires = ["setuptools", "wheel", "Cython", "ipopt", "numpy", "scipy"]  # PEP 508 specifications.
```

I based this on the following code statement: https://github.com/pycalphad/pycalphad/blob/be404461ad44a4677897a0cc0d843dd7bec1007e/setup.py#L10
You can add version requirements too but I'm not familiar enough with your dependencies to do this.

**Comment by richardotis** [comment]
Thanks for making this issue. The minimal `pyproject.toml` looks useful and I think it can be added. Can you perhaps answer some other PEP 517/518 questions? I notice some aspects of this are not well-documented. I looked at the following pages:
- https://packaging.python.org/tutorials/packaging-projects/
- https://github.com/pypa/setuptools/issues/1698
- https://www.python.org/dev/peps/pep-0517/

These are my questions:
- Do we need to add a `build-backend` directive? It looks like it will be required in the future.
- How do we read our `README.md` at build time if we no longer use `__file__` in `setup.py`?
- I see some pushing for `setup.cfg` (static file) over `setup.py` in the Python packaging docs, but is it possible for pycalphad to do that if we need to build Cython extensions? The best Cython-using package I'm aware of is spaCy ( https://github.com/explosion/spaCy/tree/1b0d413e45e1495d58a6756f4f1dad82953a9bb6 ) and it looks like they use a `pyproject.toml` and a `setup.py` which cythonizes the extensions, similar to our current approach. They also appear to be duplicating a lot of their dependencies in `setup.cfg`, for reasons which aren't immediately clear to me.

**Comment by richardotis** [comment]
Reading the first link a little more carefully, it looks like the answer to my second question is that there's special support for reading in files in the source directory:
```
# setup.cfg
[metadata]
# replace with your username:
name = example-pkg-YOUR-USERNAME-HERE
version = 0.0.1
author = Example Author
author_email = author@example.com
description = A small example package
long_description = file: README.md
long_description_content_type = text/markdown
[snip]
```

**Comment by bocklund** [comment]
Even though we aren't officially supporting pip/PyPI installs until cyipopt/ipopt is no longer a dependency, I'm on board with this as long as we can contain all the dependencies in `pyproject.toml` and we don't have to duplicate the dependencies in both `pyproject.toml` and `setup.py`.

**Comment by toastedcrumpets** [comment]
I think there's two issues here. First, there's a "bugfix", you should have build-time dependencies specified in pyproject.toml so that pip install commands work. Second, there's "improvement" where you modernise the whole build system. I know that improvements tend to take time/stall completely, so I'm keen to focus on the "bugfix" aspect.

@bocklund Literally the only things that need to be in pyproject.toml are the C/C++ stuff you need for build, as pure python modules can typically be installed in any order as the linkages are resolved at runtime. There is almost no maintainance burden as you only depend on ipopt/cython (and need numpy/scipy for them).

**Comment by bocklund** [comment]
I think that setuptools `setup_requires` solves this particular issue with numpy, scipy, and Cython dependencies. I opened #325 to put use `setup_requires`. This still won't allow pycalphad to be built from pip yet, since we still have build dependencies on the C++ symengine and IPOPT, which cannot be installed via pip AFAIK.

My understanding is that pyproject.toml is the future, but PEP 517/518 are currently provisionally accepted and things are still subject to change. There seem to be some good benefits and use cases for some projects to make it worth transitioning to pyproject.toml, but I don't think pycalphad would benefit from it yet. IMO, we should take another look once PEP 517/518 are final or there is some new behavior that we could take advantage of.

**Comment by bocklund** [comment]
Actually, I realize now we'd have to write and maintain more code to handle calling `cythonize` only after the build tool installs from `setup_requires`, so it looks like we would have to introduce a minimal pyproject.toml as suggested by [Cython](https://cython.readthedocs.io/en/latest/src/userguide/source_files_and_compilation.html#basic-setup-py)
